import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fullstack To-do app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} container py-4 antialiased text-foreground bg-background min-h-screen items-center flex justify-center`}
      >
        <Providers>
          <Navbar />
          <main className="w-80">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
